api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    formats:
        json: ['application/json']
    swagger:
        versions: [3]
    collection:
        pagination:
            page_parameter_name: page
            items_per_page: 15
